### ISSUE TITLE
node settings not respected/working

### ISSUE THREAD

**Issue by ghvader** [MintyTrebor/NodeDSF#1]
using the DSF Monitor node to monitor my duet works, however it polls at 200ms no matter what number I put in the settings. 
also the "auto start" doesn't seem to work either. if I uncheck it and re-deploy, 200ms poll starts regardless.

**Comment by MintyTrebor** [comment]
Poll rate applies only in Duet mode, not in DSF mode, which one are you using?
Can you also confirm your version number of the dsfnodes please (latest is 1.1.2)
Which method of deploying are you using when changing the autostart option? (Full, modified nodes, or modified flows) and is this behaviour persistent if you use Deploy => restart flows?
Edit- I have just checked the code and the poll-rate is limited to a range of 200ms to 7000ms if you enter a number outside this range it will change it back to 200ms (I have no idea why I did not put that in the UI??)

**Comment by ghvader** [comment]
it appears to be working correctly after a restart restarting the flow. I did notice however that was inconsistent. updating the time sometimes works and other times I had to restart the flow manually to get the desired polling time. either way, appreciate the response. closing the issue

**Comment by MintyTrebor** [comment]
Node-red seems to be temperamental about what it considers to be a "flow restart" trigger. I often find just moving a node is enough to trigger a full restart on deploy, but changing a nodes parameters is not....go figure. Glad you got it working anyway!
