### ISSUE TITLE
Sending custom macros to DSF (e.g. M98 P"custrom_macro.g") do not work

### ISSUE THREAD

**Issue by de42** [MintyTrebor/NodeDSF#2]
When using the DSF-CMD node, macros cannot be executed. The function `M98 P"custom_macro.g"` cannot be called.
When reading the UNIX socket I get the following output:
`HTTP: M98 P"{move_to_mid.g}" => Error: M98: unknown value 'move_to_mid.g'`

I also get an error message when I specify the path to the macro:
`HTTP: M98 P"/opt/dsf/sd/macros/move_to_mid.g" => Warning: Macro file /opt/dsf/sd/macros/move_to_mid.g not found`

I can't pinpoint the error at the moment, but I don't think it's the plugin itself.

**Comment by de42** [comment]
ok, sorry. That has been solved. I specified the path to the macro incorrectly. 
Correct would be the following: 
`M98 P "0:/macros/move_to_mid.g"`

**Comment by MintyTrebor** [comment]
You beat me to it. 
I'm glad you got it working!
