### ISSUE TITLE
there is no file information under the job object in the monitor full model

### ISSUE THREAD

**Issue by hanswwilson** [MintyTrebor/NodeDSF#3]
job.file.filename doesn't seem to exist in the data of the full model coming out of the monitor

![image](https://user-images.githubusercontent.com/8825720/214465893-e37b911c-8a0e-4f57-93b3-70eb4c7903fc.png)

Connected to a duet2 ethernet using duet mode on the monitor. Originally using the most recent stable firmware [Release 3.4.5] but I have also tried rolling the firmware back to before the 1.9 release of NodeDSF in case something in the firmware updated causing the issue. Tried both [Release 3.4.2] and [Release 3.4.1] but even with those older firmware version still no job filename information. Time remaining, duet status, many other things all work okay.

Image shows "debug 8" active but the full model debug info came from the inactive "Foam Debug" I also in all 3 firmware versions had no functionality from the intercept node when using the M291 command, nor does the state.displaymessage update with a M117 command.

**Comment by MintyTrebor** [comment]
The file information from the OM is not retrieved (I do not retrieve everything to reduce load). I will see if I can add it in the update I will release when RRF 3.5 is stable.
The nodeDSF RRF messaging system for 3.4 is buggy, and has been changed/updated a number of times
I will look at the M291 issue, I suspect it will be related to the messaging issues.
Update : Yes M291 behaviour has changed in both 3.5beta and at least 3.4.5. I will resolve for the next release

**Comment by hanswwilson** [comment]
That's great to hear, I am working on a system that needs to sequence and run different gcode files continuously, my original plan which seemed the simplest was to use a M291 message at the end of each gcode file to pass the filename of the next gcode file to run, but since I couldn't get that working and M117 which also didn't seem to work, my fallback was to track everything separately but I still needed to find the filename from the job object for verification and error checking.

**Comment by MintyTrebor** [comment]
OK I think I have file info working, and have fixed M291 Interecpt & M118/M117 msgs. I'm not entirely sure which rrf version it stopped working on so I'm Gonna run some tests and if everything goes OK, I will publish tomorrow

**Comment by MintyTrebor** [comment]
Published 1.1.10
Added file info
Fixed Intercept Node
Fixed Messaging system. Now Console & M118 messages will be located in state.consoleMessage. M117 will remain in state.displayMessage.
Tested on 3.5b1 and 3.4.5 RRF versions
This should resolve your issues (I Hope)

**Comment by hanswwilson** [comment]
I have tested it myself now as well and can also confirm that with RRF 3.4.5 M291 intercepts are working as are the messaging system both M117 & M118 and all the job information is present as well, absolutely fantastic!
